#pragma once

#include <bungee/Bungee.h>

#include <array>
#include <memory>
#include <vector>

#include "engine/bufferscalers/enginebufferscale.h"
#include "util/samplebuffer.h"

class ReadAheadManager;

// Autonomously generated by an AI agent.
// Reverse playback reads reversed source samples into a forward virtual timeline.
// OutputChunk request endpoints define the audible source advance; parameter
// changes reach output after the grain pipeline, rather than immediately.
// End of autonomously generated AI text.
class EngineBufferScaleBungeeCore final : public EngineBufferScale {
  public:
    explicit EngineBufferScaleBungeeCore(ReadAheadManager* pReadAheadManager);

    EngineBufferScaleBungeeCore(const EngineBufferScaleBungeeCore&) = delete;
    EngineBufferScaleBungeeCore& operator=(const EngineBufferScaleBungeeCore&) = delete;
    EngineBufferScaleBungeeCore(EngineBufferScaleBungeeCore&&) = delete;
    EngineBufferScaleBungeeCore& operator=(EngineBufferScaleBungeeCore&&) = delete;

    ~EngineBufferScaleBungeeCore() override = default;

    void setScaleParameters(double base_rate,
            double* pTempoRatio,
            double* pPitchRatio) override;

    double scaleBuffer(CSAMPLE* pOutputBuffer,
            SINT iOutputBufferSize) override;

    double getVisualPlayPositionOffset() const;

    void clear() override;

  private:
    void onSignalChanged() override;

    SINT processGrain(CSAMPLE* pOutputBuffer, SINT maxFrames);

    void deinterleaveInput(const CSAMPLE* pBuffer, SINT destOffsetFrames, SINT frames);

    void discardBufferedInputBefore(SINT framePosition, double signedEffectiveRate = 1.0);

    SINT consumeReadAheadGap(double signedEffectiveRate, SINT framesToConsume);

    SINT appendInputFrames(double signedEffectiveRate, SINT framesToRead);

    SINT ensureInputForCurrentChunk(double signedEffectiveRate);

    void copyOutputFrames(CSAMPLE* pDest, SINT offsetInChunk, SINT nFrames) const;
    bool hasValidOutputChunk() const;
    double copyFlushOutputFrames(CSAMPLE*& pOutput, SINT& remainingFrames);

    ReadAheadManager* m_pReadAheadManager;

    std::unique_ptr<Bungee::Stretcher<Bungee::Basic>> m_pStretcher;

    Bungee::Request m_request;

    Bungee::OutputChunk m_outputChunk;

    std::vector<float*> m_channelBufferPtrs;

    mixxx::SampleBuffer m_contiguousChannelBuffer;

    mixxx::SampleBuffer m_interleavedReadBuffer;
    mixxx::SampleBuffer m_analysisBuffer;

    bool m_bBackwards;

    SINT m_channelStride;

    Bungee::InputChunk m_currentInputChunk;

    SINT m_bufferedInputBeginFrame;
    SINT m_bufferedInputEndFrame;

    bool m_bResetNeeded;

    SINT m_remainingOutputFrames;
    SINT m_outputChunkConsumed;
    double m_lastReadFramesProcessed;
    double m_outputSourceRate = 1;

    static constexpr SINT kMaxGrainFrames = 4096;

    SINT m_outputLatencyFrames;

    SINT m_inputBufferFrames;

    bool m_grainPending;
    bool m_prerolling = true;
    bool m_cacheReadUnavailable;
    int m_readAttempts;
    int m_zeroReadAttempts;
};
